import { describe, it, expect } from "vitest";
import { generateGPX } from "./gpxService";
import type { ItinerarySummaryJSON } from "../../types";

describe("gpxService", () => {
  describe("generateGPX", () => {
    it("should generate valid GPX 1.1 XML structure", () => {
      const itinerary: ItinerarySummaryJSON = {
        title: "Mountain Loop Adventure",
        days: [
          {
            day: 1,
            segments: [
              {
                name: "Start Point",
                description: "Beginning of the journey",
                distance_km: 50,
                duration_h: 1.5,
              },
              {
                name: "Mountain Pass",
                description: "Scenic mountain route",
                distance_km: 75,
                duration_h: 2.0,
              },
            ],
          },
        ],
        total_distance_km: 125,
        total_duration_h: 3.5,
        highlights: ["Mountain views", "Scenic overlook"],
      };

      const gpx = generateGPX(itinerary, "test-itinerary-id");

      // Check XML declaration
      expect(gpx).toContain('<?xml version="1.0" encoding="UTF-8"?>');

      // Check GPX version and namespace
      expect(gpx).toContain('version="1.1"');
      expect(gpx).toContain('xmlns="http://www.topografix.com/GPX/1/1"');

      // Check creator
      expect(gpx).toContain('creator="VibeRide - https://viberide.com"');
    });

    it("should include metadata with title and description", () => {
      const itinerary: ItinerarySummaryJSON = {
        title: "Test Route",
        days: [
          {
            day: 1,
            segments: [
              {
                name: "Test Segment",
                description: "Test description",
                distance_km: 100,
                duration_h: 2,
              },
            ],
          },
        ],
        total_distance_km: 100,
        total_duration_h: 2,
        highlights: [],
      };

      const gpx = generateGPX(itinerary, "test-id");

      expect(gpx).toContain("<metadata>");
      expect(gpx).toContain("<name>Test Route</name>");
      expect(gpx).toContain("<desc>Generated by VibeRide - Motorcycle trip itinerary</desc>");
      expect(gpx).toContain("<author>");
      expect(gpx).toContain("<name>VibeRide</name>");
    });

    it("should generate waypoints for each segment", () => {
      const itinerary: ItinerarySummaryJSON = {
        title: "Test Route",
        days: [
          {
            day: 1,
            segments: [
              {
                name: "Waypoint 1",
                description: "First stop",
                distance_km: 50,
                duration_h: 1,
              },
              {
                name: "Waypoint 2",
                description: "Second stop",
                distance_km: 50,
                duration_h: 1,
              },
            ],
          },
        ],
        total_distance_km: 100,
        total_duration_h: 2,
        highlights: [],
      };

      const gpx = generateGPX(itinerary, "test-id");

      // Check waypoints
      expect(gpx).toContain("<wpt lat=");
      expect(gpx).toContain("<name>Waypoint 1</name>");
      expect(gpx).toContain("<desc>First stop</desc>");
      expect(gpx).toContain("<name>Waypoint 2</name>");
      expect(gpx).toContain("<desc>Second stop</desc>");
      expect(gpx).toContain("<type>waypoint</type>");
    });

    it("should generate route with route points", () => {
      const itinerary: ItinerarySummaryJSON = {
        title: "Test Route",
        days: [
          {
            day: 1,
            segments: [
              {
                name: "Point A",
                description: "Start",
                distance_km: 50,
                duration_h: 1,
              },
            ],
          },
        ],
        total_distance_km: 50,
        total_duration_h: 1,
        highlights: [],
      };

      const gpx = generateGPX(itinerary, "test-id");

      expect(gpx).toContain("<rte>");
      expect(gpx).toContain("<rtept lat=");
      expect(gpx).toContain("Total distance: 50.0 km");
      expect(gpx).toContain("Duration: 1.0 hours");
    });

    it("should escape XML special characters in names and descriptions", () => {
      const itinerary: ItinerarySummaryJSON = {
        title: 'Route with <special> & "characters"',
        days: [
          {
            day: 1,
            segments: [
              {
                name: "Point <A>",
                description: 'Description with & and "quotes"',
                distance_km: 50,
                duration_h: 1,
              },
            ],
          },
        ],
        total_distance_km: 50,
        total_duration_h: 1,
        highlights: [],
      };

      const gpx = generateGPX(itinerary, "test-id");

      // Check that special characters are escaped
      expect(gpx).toContain("&lt;special&gt;");
      expect(gpx).toContain("&amp;");
      expect(gpx).toContain("&quot;");
      expect(gpx).not.toContain("<special>");
      expect(gpx).not.toContain("& ");
    });

    it("should handle multiple days with multiple segments", () => {
      const itinerary: ItinerarySummaryJSON = {
        title: "Multi-day Trip",
        days: [
          {
            day: 1,
            segments: [
              {
                name: "Day 1 - Segment 1",
                description: "First day first segment",
                distance_km: 50,
                duration_h: 1,
              },
              {
                name: "Day 1 - Segment 2",
                description: "First day second segment",
                distance_km: 50,
                duration_h: 1,
              },
            ],
          },
          {
            day: 2,
            segments: [
              {
                name: "Day 2 - Segment 1",
                description: "Second day first segment",
                distance_km: 60,
                duration_h: 1.5,
              },
            ],
          },
        ],
        total_distance_km: 160,
        total_duration_h: 3.5,
        highlights: [],
      };

      const gpx = generateGPX(itinerary, "test-id");

      // With intermediate points, we now have more waypoints and route points
      // 3 segments: each generates start + intermediate points + end
      // Segment 1 (50km): start + 2 intermediate + end = 4 points
      // Segment 2 (50km): start + 2 intermediate (end merged with day end) = 3 points
      // Segment 3 (60km): start + 3 intermediate + end = 4 points
      // But waypoints only include start/end points (not intermediate)
      const waypointMatches = gpx.match(/<wpt lat=/g);
      expect(waypointMatches).not.toBeNull();
      expect(waypointMatches!.length).toBeGreaterThan(3); // More than just segment starts

      // Route points include all points (start, intermediate, end)
      const routePointMatches = gpx.match(/<rtept lat=/g);
      expect(routePointMatches).not.toBeNull();
      expect(routePointMatches!.length).toBeGreaterThan(3); // Includes intermediate points

      // Check all segment names are present
      expect(gpx).toContain("Day 1 - Segment 1");
      expect(gpx).toContain("Day 1 - Segment 2");
      expect(gpx).toContain("Day 2 - Segment 1");
    });

    it("should handle empty itinerary", () => {
      const itinerary: ItinerarySummaryJSON = {
        title: "Empty Route",
        days: [
          {
            day: 1,
            segments: [
              {
                name: "Minimal Segment",
                description: "At least one segment for valid GPX",
                distance_km: 0,
                duration_h: 0,
              },
            ],
          },
        ],
        total_distance_km: 0,
        total_duration_h: 0,
        highlights: [],
      };

      const gpx = generateGPX(itinerary, "test-id");

      // Should still generate valid GPX structure
      expect(gpx).toContain('<?xml version="1.0"');
      expect(gpx).toContain("<metadata>");
      expect(gpx).toContain("<rte>");
      expect(gpx).toContain("Total distance: 0.0 km");
    });

    it("should generate different coordinates for each waypoint", () => {
      const itinerary: ItinerarySummaryJSON = {
        title: "Test Route",
        days: [
          {
            day: 1,
            segments: [
              { name: "A", description: "First", distance_km: 10, duration_h: 0.5 },
              { name: "B", description: "Second", distance_km: 10, duration_h: 0.5 },
              { name: "C", description: "Third", distance_km: 10, duration_h: 0.5 },
            ],
          },
        ],
        total_distance_km: 30,
        total_duration_h: 1.5,
        highlights: [],
      };

      const gpx = generateGPX(itinerary, "test-id");

      // Extract coordinates
      const latMatches = gpx.match(/lat="([^"]+)"/g);
      const lonMatches = gpx.match(/lon="([^"]+)"/g);

      // With intermediate points, we have more coordinates
      // Each 10km segment gets 1 intermediate point
      expect(latMatches).not.toBeNull();
      expect(lonMatches).not.toBeNull();
      expect(latMatches!.length).toBeGreaterThan(6); // More than just start/end
      expect(lonMatches!.length).toBeGreaterThan(6);

      // Check that coordinates are different (not all the same)
      const uniqueLats = new Set(latMatches);
      expect(uniqueLats.size).toBeGreaterThan(1);
    });
  });
});
