import type { ItinerarySummaryJSON } from "../../types";

/**
 * GPX Service
 * Generates GPX 1.1 XML files from itinerary data
 */

/**
 * Generates a GPX 1.1 XML string from an itinerary
 * 
 * Note: This is a simplified GPX generation for MVP.
 * Since the itinerary doesn't contain actual GPS coordinates,
 * we generate waypoints with placeholder coordinates based on segment names.
 * 
 * In production, this would:
 * - Use actual GPS coordinates from route planning
 * - Include elevation data
 * - Add track points between waypoints
 * - Include proper route metadata
 * 
 * @param itinerary The itinerary summary to convert to GPX
 * @param itineraryId The ID of the itinerary (used in metadata)
 * @returns GPX 1.1 XML string
 */
export function generateGPX(itinerary: ItinerarySummaryJSON, itineraryId: string): string {
  const now = new Date().toISOString();
  
  // Extract waypoints from segments
  const waypoints: Array<{ name: string; description: string; index: number }> = [];
  let waypointIndex = 0;
  
  itinerary.days.forEach((day) => {
    day.segments.forEach((segment) => {
      waypoints.push({
        name: segment.name,
        description: segment.description,
        index: waypointIndex++,
      });
    });
  });

  // Generate GPX XML
  const gpxXml = `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" 
     creator="VibeRide - https://viberide.com" 
     xmlns="http://www.topografix.com/GPX/1/1"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <metadata>
    <name>${escapeXml(itinerary.title)}</name>
    <desc>Generated by VibeRide - Motorcycle trip itinerary</desc>
    <author>
      <name>VibeRide</name>
      <link href="https://viberide.com">
        <text>VibeRide</text>
      </link>
    </author>
    <time>${now}</time>
    <keywords>motorcycle,trip,itinerary,route</keywords>
  </metadata>
${generateWaypoints(waypoints)}
  <rte>
    <name>${escapeXml(itinerary.title)}</name>
    <desc>Total distance: ${itinerary.total_distance_km.toFixed(1)} km, Duration: ${itinerary.total_duration_h.toFixed(1)} hours</desc>
${generateRoutePoints(waypoints)}
  </rte>
</gpx>`;

  return gpxXml;
}

/**
 * Generates waypoint XML elements
 * Uses placeholder coordinates in a grid pattern
 */
function generateWaypoints(waypoints: Array<{ name: string; description: string; index: number }>): string {
  return waypoints
    .map((wp) => {
      // Generate placeholder coordinates
      // In production, these would be actual GPS coordinates
      const lat = 45.0 + (wp.index * 0.1); // Placeholder latitude
      const lon = -93.0 + (wp.index * 0.1); // Placeholder longitude
      
      return `  <wpt lat="${lat.toFixed(6)}" lon="${lon.toFixed(6)}">
    <name>${escapeXml(wp.name)}</name>
    <desc>${escapeXml(wp.description)}</desc>
    <type>waypoint</type>
  </wpt>`;
    })
    .join("\n");
}

/**
 * Generates route point XML elements
 */
function generateRoutePoints(waypoints: Array<{ name: string; description: string; index: number }>): string {
  return waypoints
    .map((wp) => {
      const lat = 45.0 + (wp.index * 0.1);
      const lon = -93.0 + (wp.index * 0.1);
      
      return `    <rtept lat="${lat.toFixed(6)}" lon="${lon.toFixed(6)}">
      <name>${escapeXml(wp.name)}</name>
      <desc>${escapeXml(wp.description)}</desc>
    </rtept>`;
    })
    .join("\n");
}

/**
 * Escapes special XML characters
 */
function escapeXml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

